# Edit this file to set the Messenger's module settings programmatically instead of using the GUI
# This is regular YAML syntax. See http://docs.ansible.com/ansible/YAMLSyntax.html
# You can override these settings with ENV variables. They are commented below.

hostname: "bots.pagekite.me/"
applicationID: "215911582291505"
accessToken: "EAADEXtUqVjEBADlJ8xlEqAt222t3IWwOWQU8JFp9biKuXhLYfdpeHJ9EgudlkQxKS8Yu8njhkCqCvvTJg7EHnoEyzj6DsSPDa0ZA6NtD4URzpgcCs7TZBdUDKyfPCZBYH3BolD6Dkso81JMmUVchZChim6BPVAV2cDWuSZAdslgZDZD"
appSecret: "5013ac8c08469f9080d1b6ee74790218"
verifyToken: "cmp-bots"

displayGetStarted: true
greetingMessage: "Greeting Message"
persistentMenu: true
persistentMenuItems:
  - 
    title: "My Adventure"
    type: "nested"
    call_to_actions: 
      - 
        title: "Scan Stamp"
        type: "postback"
        payload: "SCAN_STAMP"
      - 
        title: "Check Progress"
        type: "postback"
        payload: "CHECK_PROGRESS"
      - 
        title: "Upcoming Opportunities"
        type: "postback"
        payload: "OPPORTUNITIES"
  - 
    title: "FAQ"
    type: "nested"
    call_to_actions: 
      - 
        title: "About Summer Adventure"
        type: "postback"
        payload: "ABOUT_SUMMER_ADVENTURE"
      - 
        title: "Museum of Art"
        type: "postback"
        payload: "ABOUT_CMOA"
      - 
        title: "Andy Warhol"
        type: "postback"
        payload: "ABOUT_WARHOL"
      - 
        title: "Membership"
        type: "postback"
        payload: "ABOUT_MEMBERSHIP"
  - 
    type: "web_url"
    title: "Website"
    url: "https://www.carnegiemuseums.org/"
    webview_height_ratio: "full"


trustedDomains: ["https://andybot.org"]
autoRespondGetStarted: true

chatExtensionHomeUrl: "https://andybot.org"
chatExtensionInTest: true
chatExtensionShowShareButton: true

enabled: true